# Generated by Django 3.2.15 on 2022-09-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kacebook_app', '0002_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
