# Generated by Django 3.2.15 on 2022-09-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kacebook_app', '0003_message_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='owner',
        ),
    ]
